shallow_clone: true

os:
  - Visual Studio 2015

environment:
  matrix:
  - TOOLSET: vs2012
  - TOOLSET: vs2013
  - TOOLSET: vs2015

configuration:
  - Debug
  - Release

install:
  - git clone https://github.com/bkaradzic/bx ..\bx
  - cd build
  - ..\..\bx\tools\bin\windows\genie vs2015 sff

build:
  project: build/$(TOOLSET)/ImWindow.sln
